import numpy as np
import os, sys

"""
Given the input arguments generated by quest2klfield.py, run the main
method in rand_field.py, generate sboom-readable files, and place them
in each appropriate case directory.

Atmosphere files are simply:
A1  P1
A2  P2
A3  P3
..  ..
AN  PN

Note that if pressure and temp both specified, they need the same 
number of pairs. But we'll probably use the same grid for everything
anyway. Need to find out what to call these files, or whatever other
way that these need to be specified.
"""






